[versions]
aboutlibraries = "11.6.3"
activityKtxVersion = "1.10.1"
activityVersion = "1.10.1"
androidGradlePlugin = "8.8.2"
appcompat = "1.7.0"
biometric = "1.4.0-alpha02"
browserVersion = "1.8.0"
coilVersion = "3.1.0"
commonsCompressVersion = "1.27.1"
commonsIoVersion = "2.18.0"
composeBomVersion = "2025.02.00"
constraintlayout = "2.2.1"
coreKtx = "1.15.0"
coreSplashscreen = "1.1.0-rc01"
datastorePreferences = "1.1.3"
espressoCore = "3.6.1"
firebaseBom = "33.9.0"
fragmentKtx = "1.8.6"
githubApiVersion = "1.327"
googleServices = "4.4.2"
gson = "2.12.1"
jsoupVersion = "1.18.3"
junit = "4.13.2"
junitVersion = "1.2.1"
konaCryptoVersion = "1.0.16"
konaProviderVersion = "1.0.16"
kotlinVersion = "2.1.10"
kotlinxCoroutinesAndroid = "1.10.1"
kotlinxSerializationJson = "1.8.0"
library = "1.3.0"
lifecycleRuntimeKtx = "2.8.7"
material = "1.13.0-alpha11"
material3Version = "1.4.0-alpha09"
mavenArtifact = "3.9.9"
oapiJavaSdkVersion = "release-V4-2.3.3"
okhttp = "4.12.0"
panguVersion = "1.1.0"
paris = "2.0.2"
recyclerview = "1.4.0"
runtimeLivedataVersion = "1.7.8"
secretsGradlePlugin = "2.0.1"
smaliDexlib2Version = "3.0.9"
uiGraphicsVersion = "1.7.8"
uiVersion = "1.7.8"
viewpager2 = "1.1.0"

[libraries]
aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutlibraries" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityKtxVersion" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtxVersion" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browserVersion" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBomVersion" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3Version" }
androidx-material3-window-sizeclass = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3Version" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLivedataVersion" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "uiVersion" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "uiGraphicsVersion" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "uiVersion" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "uiVersion" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
coil = { module = "io.coil-kt.coil3:coil", version.ref = "coilVersion" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilVersion" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commonsCompressVersion" }
commons-io = { module = "commons-io:commons-io", version.ref = "commonsIoVersion" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
github-api = { module = "org.kohsuke:github-api", version.ref = "githubApiVersion" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoupVersion" }
junit = { module = "junit:junit", version.ref = "junit" }
kona-crypto = { module = "com.tencent.kona:kona-crypto", version.ref = "konaCryptoVersion" }
kona-provider = { module = "com.tencent.kona:kona-provider", version.ref = "konaProviderVersion" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
library = { module = "me.zhanghai.android.fastscroll:library", version.ref = "library" }
material = { module = "com.google.android.material:material", version.ref = "material" }
maven-artifact = { module = "org.apache.maven:maven-artifact", version.ref = "mavenArtifact" }
oapi-java-sdk = { module = "cn.bigmodel.openapi:oapi-java-sdk", version.ref = "oapiJavaSdkVersion" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
pangu = { module = "ws.vinta:pangu", version.ref = "panguVersion" }
paris = { module = "com.airbnb.android:paris", version.ref = "paris" }
secrets-gradle-plugin = { module = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin", version.ref = "secretsGradlePlugin" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activityVersion" }
smali-dexlib2 = { module = "com.android.tools.smali:smali-dexlib2", version.ref = "smaliDexlib2Version" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

[plugins]
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinVersion" }
